name = "Stat_Mech_II_NTHU"
uuid = "99f9a0c3-d6b3-46f3-a95e-ba762f2dd50a"
authors = ["Yi-Ping Huang"]
version = "1.0.0-DEV"

[deps]
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[compat]
LiveServer = "1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
